name: Pact-Rust Compatibility Suite

on: [
  # push, 
  # pull_request
  workflow_dispatch
  ]

jobs:
  v1:
    runs-on: ubuntu-latest
    env:
      pact_do_not_track: true
    steps:
    - uses: actions/checkout@v2
    - uses: dtolnay/rust-toolchain@stable
    - name: Run Cucumber
      run: cargo test --test v1*
      working-directory: compatibility-suite
  v2:
    runs-on: ubuntu-latest
    env:
      pact_do_not_track: true
    steps:
      - uses: actions/checkout@v2
      - uses: dtolnay/rust-toolchain@stable
      - name: Run Cucumber
        run: cargo test --test v2*
        working-directory: compatibility-suite
  v3:
    runs-on: ubuntu-latest
    env:
      pact_do_not_track: true
    steps:
      - uses: actions/checkout@v2
      - uses: dtolnay/rust-toolchain@stable
      - name: Run Cucumber
        run: cargo test --test v3*
        working-directory: compatibility-suite
